[[annotation]]
file="dust.bed.gz"
columns = [4]
names=["dust"]
ops=["flag"]

[[annotation]]
file="repeat_masker.bed.gz"
columns = [4]
names=["repeat_masker"]
ops=["flag"]


[[annotation]]
file= "BCSQ_bed.bed.gz"
columns=[4,5,6]
ops=["self", "self", "self"]
names=["BLOSUM", "Grantham", "Percent_Protein"]
